const {PrismaClient} = require('@prisma/client')
const {chat, message} = new PrismaClient()

const CHATS = [
  {
    id: 1,
    title: 'Animal chat',
    userIds: [
      1, 2
    ],
    messages: [
      {"userId":2,"message":"Jay"},
      {"userId":1,"message":"Toban"},
      {"userId":2,"message":"Bobwhite"},
      {"userId":1,"message":"Donald"},
      {"userId":2,"message":"Jenifer"},
      {"userId":1,"message":"Rieder"},
      {"userId":2,"message":"Debs"},
      {"userId":1,"message":"Onsgard"},
      {"userId":2,"message":"Hoepker"},
      {"userId":1,"message":"Menomonie"},
      {"userId":2,"message":"Oakridge"},
      {"userId":1,"message":"Eggendart"},
      {"userId":2,"message":"Sheridan"},
      {"userId":1,"message":"Gateway"},
      {"userId":2,"message":"Fulton"},
      {"userId":1,"message":"Briar Crest"},
      {"userId":2,"message":"Jenna"},
      {"userId":1,"message":"Waxwing"},
      {"userId":2,"message":"High Crossing"},
      {"userId":1,"message":"Waywood"},
      {"userId":2,"message":"Sloan"},
      {"userId":1,"message":"Buell"},
      {"userId":2,"message":"Steensland"},
      {"userId":1,"message":"Drewry"},
      {"userId":2,"message":"Artisan"},
      {"userId":1,"message":"Vera"},
      {"userId":2,"message":"Dawn"},
      {"userId":1,"message":"Northwestern"},
      {"userId":2,"message":"Boyd"},
      {"userId":1,"message":"Veith"},
      {"userId":2,"message":"Mccormick"},
      {"userId":1,"message":"Park Meadow"},
      {"userId":2,"message":"Shoshone"},
      {"userId":1,"message":"Meadow Vale"},
      {"userId":2,"message":"Boyd"},
      {"userId":1,"message":"Waxwing"},
      {"userId":2,"message":"Namekagon"},
      {"userId":1,"message":"Ryan"},
      {"userId":2,"message":"Rigney"},
      {"userId":1,"message":"Messerschmidt"},
      {"userId":2,"message":"Eliot"},
      {"userId":1,"message":"Vermont"},
      {"userId":2,"message":"Kropf"},
      {"userId":1,"message":"Tennessee"},
      {"userId":2,"message":"Grim"},
      {"userId":1,"message":"Lukken"},
      {"userId":2,"message":"Atwood"},
      {"userId":1,"message":"Northview"},
      {"userId":2,"message":"North"},
      {"userId":1,"message":"Holy Cross"},
      {"userId":2,"message":"Old Shore"},
      {"userId":1,"message":"Del Sol"},
      {"userId":2,"message":"Welch"},
      {"userId":1,"message":"Golden Leaf"},
      {"userId":2,"message":"Clemons"},
      {"userId":1,"message":"Sutteridge"},
      {"userId":2,"message":"Elgar"},
      {"userId":1,"message":"Kingsford"},
      {"userId":2,"message":"Kings"},
      {"userId":1,"message":"6th"},
      {"userId":2,"message":"Loftsgordon"},
      {"userId":1,"message":"Comanche"},
      {"userId":2,"message":"Mallard"},
      {"userId":1,"message":"Fuller"},
      {"userId":2,"message":"Hintze"},
      {"userId":1,"message":"Reindahl"},
      {"userId":2,"message":"Cody"},
      {"userId":1,"message":"High Crossing"},
      {"userId":2,"message":"Haas"},
      {"userId":1,"message":"Warner"},
      {"userId":2,"message":"Boyd"},
      {"userId":1,"message":"Holmberg"},
      {"userId":2,"message":"Harbort"},
      {"userId":1,"message":"Huxley"},
      {"userId":2,"message":"Acker"},
      {"userId":1,"message":"Pleasure"},
      {"userId":2,"message":"Forster"},
      {"userId":1,"message":"Helena"},
      {"userId":2,"message":"Leroy"},
      {"userId":1,"message":"Fair Oaks"},
      {"userId":2,"message":"Judy"},
      {"userId":1,"message":"Derek"},
      {"userId":2,"message":"Sundown"},
      {"userId":1,"message":"Banding"},
      {"userId":2,"message":"Lotheville"},
      {"userId":1,"message":"Longview"},
      {"userId":2,"message":"Shopko"},
      {"userId":1,"message":"Judy"},
      {"userId":2,"message":"Myrtle"},
      {"userId":1,"message":"Mccormick"},
      {"userId":2,"message":"Bellgrove"},
      {"userId":1,"message":"Colorado"},
      {"userId":2,"message":"Melby"},
      {"userId":1,"message":"Ridge Oak"},
      {"userId":2,"message":"Golden Leaf"},
      {"userId":1,"message":"Spaight"},
      {"userId":2,"message":"Mayer"},
      {"userId":1,"message":"Daystar"},
      {"userId":2,"message":"International"},
      {"userId":1,"message":"Lyons"},
      {"userId":2,"message":"Northview"},
      {"userId":1,"message":"Nova"},
      {"userId":2,"message":"Menomonie"},
      {"userId":1,"message":"Nelson"},
      {"userId":2,"message":"Sunbrook"},
      {"userId":1,"message":"Upham"},
      {"userId":2,"message":"Rutledge"},
      {"userId":1,"message":"Bayside"},
      {"userId":2,"message":"Di Loreto"},
      {"userId":1,"message":"Service"},
      {"userId":2,"message":"Hovde"},
      {"userId":1,"message":"Dorton"},
      {"userId":2,"message":"Hansons"},
      {"userId":1,"message":"Buena Vista"},
      {"userId":2,"message":"Rigney"},
      {"userId":1,"message":"Warrior"},
      {"userId":2,"message":"Green Ridge"},
      {"userId":1,"message":"Shelley"},
      {"userId":2,"message":"Anniversary"},
      {"userId":1,"message":"Glendale"},
      {"userId":2,"message":"Troy"},
      {"userId":1,"message":"Carey"},
      {"userId":2,"message":"Grayhawk"},
      {"userId":1,"message":"Northwestern"},
      {"userId":2,"message":"Forest"},
      {"userId":1,"message":"Roxbury"},
      {"userId":2,"message":"Carberry"},
      {"userId":1,"message":"Mccormick"},
      {"userId":2,"message":"Mayfield"},
      {"userId":1,"message":"Susan"},
      {"userId":2,"message":"Onsgard"},
      {"userId":1,"message":"Stuart"},
      {"userId":2,"message":"Hazelcrest"},
      {"userId":1,"message":"Anderson"},
      {"userId":2,"message":"Golden Leaf"},
      {"userId":1,"message":"Clyde Gallagher"},
      {"userId":2,"message":"Pennsylvania"},
      {"userId":1,"message":"Mallory"},
      {"userId":2,"message":"Bartillon"},
      {"userId":1,"message":"Sutteridge"},
      {"userId":2,"message":"Thackeray"},
      {"userId":1,"message":"Tony"},
      {"userId":2,"message":"Summer Ridge"},
      {"userId":1,"message":"Waubesa"},
      {"userId":2,"message":"East"},
      {"userId":1,"message":"Luster"},
      {"userId":2,"message":"Sloan"},
      {"userId":1,"message":"Oakridge"},
      {"userId":2,"message":"Arkansas"},
      {"userId":1,"message":"Maple"},
      {"userId":2,"message":"Oak Valley"},
      {"userId":1,"message":"Arkansas"},
      {"userId":2,"message":"Sommers"},
      {"userId":1,"message":"Dryden"},
      {"userId":2,"message":"Bartillon"},
      {"userId":1,"message":"Ridgeway"},
      {"userId":2,"message":"Bonner"},
      {"userId":1,"message":"Westridge"},
      {"userId":2,"message":"Lerdahl"},
      {"userId":1,"message":"Eagan"},
      {"userId":2,"message":"Wayridge"},
      {"userId":1,"message":"Elgar"},
      {"userId":2,"message":"Laurel"},
      {"userId":1,"message":"Eagle Crest"},
      {"userId":2,"message":"Mitchell"},
      {"userId":1,"message":"Fremont"},
      {"userId":2,"message":"Waywood"},
      {"userId":1,"message":"Sutteridge"},
      {"userId":2,"message":"Holmberg"},
      {"userId":1,"message":"Westport"},
      {"userId":2,"message":"Talisman"},
      {"userId":1,"message":"Forest"},
      {"userId":2,"message":"Independence"},
      {"userId":1,"message":"International"},
      {"userId":2,"message":"Columbus"},
      {"userId":1,"message":"Norway Maple"},
      {"userId":2,"message":"Magdeline"},
      {"userId":1,"message":"Pawling"},
      {"userId":2,"message":"Maple Wood"},
      {"userId":1,"message":"Sycamore"},
      {"userId":2,"message":"Trailsway"},
      {"userId":1,"message":"Oak"},
      {"userId":2,"message":"Kipling"},
      {"userId":1,"message":"Upham"},
      {"userId":2,"message":"3rd"},
      {"userId":1,"message":"Grasskamp"},
      {"userId":2,"message":"Melby"},
      {"userId":1,"message":"Columbus"},
      {"userId":2,"message":"Fallview"},
      {"userId":1,"message":"Linden"},
      {"userId":2,"message":"Green"},
      {"userId":1,"message":"Norway Maple"},
      {"userId":2,"message":"Spohn"},
      {"userId":1,"message":"Thompson"},
      {"userId":2,"message":"Stone Corner"},
      {"userId":1,"message":"Loftsgordon"},
      {"userId":2,"message":"Eastlawn"},
      {"userId":1,"message":"Chinook"},
      {"userId":2,"message":"Karstens"},
      {"userId":1,"message":"Hagan"},
      {"userId":2,"message":"Dahle"},
      {"userId":1,"message":"Green"},
      {"userId":2,"message":"Stephen"},
      {"userId":1,"message":"Pine View"},
      {"userId":2,"message":"Shoshone"},
      {"userId":1,"message":"Porter"},
      {"userId":2,"message":"Westerfield"},
      {"userId":1,"message":"Butterfield"},
      {"userId":2,"message":"Mccormick"},
      {"userId":1,"message":"Spohn"},
      {"userId":2,"message":"Loomis"},
      {"userId":1,"message":"David"},
      {"userId":2,"message":"Holy Cross"},
      {"userId":1,"message":"Sachs"},
      {"userId":2,"message":"Dapin"},
      {"userId":1,"message":"Oneill"},
      {"userId":2,"message":"Melody"},
      {"userId":1,"message":"Pine View"},
      {"userId":2,"message":"Dovetail"},
      {"userId":1,"message":"Buell"},
      {"userId":2,"message":"4th"},
      {"userId":1,"message":"Portage"},
      {"userId":2,"message":"Dawn"},
      {"userId":1,"message":"Hallows"},
      {"userId":2,"message":"Fordem"},
      {"userId":1,"message":"Katie"},
      {"userId":2,"message":"Calypso"},
      {"userId":1,"message":"Cody"},
      {"userId":2,"message":"Sunfield"},
      {"userId":1,"message":"Main"},
      {"userId":2,"message":"Rowland"},
      {"userId":1,"message":"Sundown"},
      {"userId":2,"message":"Vahlen"},
      {"userId":1,"message":"Coolidge"},
      {"userId":2,"message":"Rieder"},
      {"userId":1,"message":"Mallory"},
      {"userId":2,"message":"Loeprich"},
      {"userId":1,"message":"Mifflin"},
      {"userId":2,"message":"Becker"},
      {"userId":1,"message":"Express"},
      {"userId":2,"message":"La Follette"},
      {"userId":1,"message":"Mariners Cove"},
      {"userId":2,"message":"Mayfield"},
      {"userId":1,"message":"Melvin"},
      {"userId":2,"message":"Sachs"},
      {"userId":1,"message":"Center"},
      {"userId":2,"message":"Saint Paul"},
      {"userId":1,"message":"Homewood"},
      {"userId":2,"message":"Oakridge"},
      {"userId":1,"message":"Graedel"},
    ],
    last_message: '',
    imageUrl: 'https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png'
  },
  {
    id: 2,
    title: 'Other chat',
    userIds: [1, 2],
    messages: [
      {"userId":2,"message":"Fairview"},
      {"userId":1,"message":"Division"},
      {"userId":2,"message":"Prairie Rose"},
      {"userId":1,"message":"Lindbergh"},
      {"userId":2,"message":"Sunnyside"},
      {"userId":1,"message":"Esch"},
      {"userId":2,"message":"Bashford"},
      {"userId":1,"message":"Marcy"},
      {"userId":2,"message":"Clove"},
      {"userId":1,"message":"Schlimgen"},
      {"userId":2,"message":"Prairie Rose"},
      {"userId":1,"message":"Butterfield"},
      {"userId":2,"message":"Heath"},
      {"userId":1,"message":"Del Sol"},
      {"userId":2,"message":"Oneill"},
      {"userId":1,"message":"Kings"},
      {"userId":2,"message":"South"},
      {"userId":1,"message":"Spenser"},
      {"userId":2,"message":"Fieldstone"},
      {"userId":1,"message":"La Follette"},
      {"userId":2,"message":"Southridge"},
      {"userId":1,"message":"Petterle"},
      {"userId":2,"message":"Esch"},
      {"userId":1,"message":"Oak"},
      {"userId":2,"message":"Hoepker"},
      {"userId":1,"message":"Corscot"},
      {"userId":2,"message":"Golden Leaf"},
      {"userId":1,"message":"Graceland"},
      {"userId":2,"message":"Summer Ridge"},
      {"userId":1,"message":"Arapahoe"},
      {"userId":2,"message":"Southridge"},
      {"userId":1,"message":"5th"},
      {"userId":2,"message":"Carioca"},
      {"userId":1,"message":"Green Ridge"},
      {"userId":2,"message":"Heffernan"},
      {"userId":1,"message":"Hooker"},
      {"userId":2,"message":"Lunder"},
      {"userId":1,"message":"Iowa"},
      {"userId":2,"message":"Hayes"},
      {"userId":1,"message":"John Wall"},
      {"userId":2,"message":"Jenifer"},
      {"userId":1,"message":"Steensland"},
      {"userId":2,"message":"Manitowish"},
      {"userId":1,"message":"Cardinal"},
      {"userId":2,"message":"Shasta"},
      {"userId":1,"message":"Mayfield"},
      {"userId":2,"message":"Maryland"},
      {"userId":1,"message":"Maryland"},
      {"userId":2,"message":"Dakota"},
      {"userId":1,"message":"Hooker"},
      {"userId":2,"message":"Dapin"},
      {"userId":1,"message":"Pond"},
      {"userId":2,"message":"Loftsgordon"},
      {"userId":1,"message":"Lakewood"},
      {"userId":2,"message":"7th"},
      {"userId":1,"message":"Farwell"},
      {"userId":2,"message":"Troy"},
      {"userId":1,"message":"Village Green"},
      {"userId":2,"message":"Welch"},
      {"userId":1,"message":"Roxbury"},
      {"userId":2,"message":"Oakridge"},
      {"userId":1,"message":"Mifflin"},
      {"userId":2,"message":"Spaight"},
      {"userId":1,"message":"Sloan"},
      {"userId":2,"message":"Garrison"},
      {"userId":1,"message":"Fieldstone"},
      {"userId":2,"message":"Park Meadow"},
      {"userId":1,"message":"Amoth"},
      {"userId":2,"message":"Mendota"},
      {"userId":1,"message":"Golf Course"},
      {"userId":2,"message":"Sunbrook"},
      {"userId":1,"message":"Hayes"},
      {"userId":2,"message":"Elka"},
      {"userId":1,"message":"Beilfuss"},
      {"userId":2,"message":"Florence"},
      {"userId":1,"message":"Main"},
      {"userId":2,"message":"Loeprich"},
      {"userId":1,"message":"Straubel"},
      {"userId":2,"message":"Rusk"},
      {"userId":1,"message":"Lyons"},
      {"userId":2,"message":"Di Loreto"},
      {"userId":1,"message":"Roth"},
      {"userId":2,"message":"Badeau"},
      {"userId":1,"message":"Old Shore"},
      {"userId":2,"message":"Northwestern"},
      {"userId":1,"message":"Westport"},
      {"userId":2,"message":"Duke"},
      {"userId":1,"message":"Division"},
      {"userId":2,"message":"Coolidge"},
      {"userId":1,"message":"Northwestern"},
      {"userId":2,"message":"Golf Course"},
      {"userId":1,"message":"Jana"},
      {"userId":2,"message":"Corben"},
      {"userId":1,"message":"Armistice"},
      {"userId":2,"message":"Brown"},
      {"userId":1,"message":"Stuart"},
      {"userId":2,"message":"Roth"},
      {"userId":1,"message":"Sunbrook"},
      {"userId":2,"message":"Texas"},
      {"userId":1,"message":"Ryan"},
      {"userId":2,"message":"Eagan"},
      {"userId":1,"message":"Moulton"},
      {"userId":2,"message":"Buhler"},
      {"userId":1,"message":"Cardinal"},
      {"userId":2,"message":"Raven"},
      {"userId":1,"message":"Browning"},
      {"userId":2,"message":"Mosinee"},
      {"userId":1,"message":"Vernon"},
      {"userId":2,"message":"Crownhardt"},
      {"userId":1,"message":"Nobel"},
      {"userId":2,"message":"Elmside"},
      {"userId":1,"message":"Schiller"},
      {"userId":2,"message":"Susan"},
      {"userId":1,"message":"Texas"},
      {"userId":2,"message":"Kedzie"},
      {"userId":1,"message":"Melrose"},
      {"userId":2,"message":"Corben"},
      {"userId":1,"message":"Calypso"},
      {"userId":2,"message":"Cottonwood"},
      {"userId":1,"message":"Carey"},
      {"userId":2,"message":"Loftsgordon"},
      {"userId":1,"message":"Jackson"},
      {"userId":2,"message":"Lien"},
      {"userId":1,"message":"Blackbird"},
      {"userId":2,"message":"Transport"},
      {"userId":1,"message":"Longview"},
      {"userId":2,"message":"Lunder"},
      {"userId":1,"message":"Oakridge"},
      {"userId":2,"message":"Autumn Leaf"},
      {"userId":1,"message":"Glendale"},
      {"userId":2,"message":"6th"},
      {"userId":1,"message":"Welch"},
      {"userId":2,"message":"Sunnyside"},
      {"userId":1,"message":"Dapin"},
      {"userId":2,"message":"Stuart"},
      {"userId":1,"message":"Darwin"},
      {"userId":2,"message":"Melrose"},
      {"userId":1,"message":"Mesta"},
      {"userId":2,"message":"Holy Cross"},
      {"userId":1,"message":"Straubel"},
      {"userId":2,"message":"Debs"},
      {"userId":1,"message":"Pond"},
      {"userId":2,"message":"Mendota"},
      {"userId":1,"message":"Saint Paul"},
      {"userId":2,"message":"Artisan"},
      {"userId":1,"message":"Starling"},
      {"userId":2,"message":"Burning Wood"},
      {"userId":1,"message":"American Ash"},
      {"userId":2,"message":"Valley Edge"},
      {"userId":1,"message":"Caliangt"},
      {"userId":2,"message":"Morningstar"},
      {"userId":1,"message":"Northwestern"},
      {"userId":2,"message":"Ronald Regan"},
      {"userId":1,"message":"Rigney"},
      {"userId":2,"message":"Jay"},
      {"userId":1,"message":"Crownhardt"},
      {"userId":2,"message":"Blue Bill Park"},
      {"userId":1,"message":"Everett"},
      {"userId":2,"message":"Commercial"},
      {"userId":1,"message":"Cordelia"},
      {"userId":2,"message":"Anhalt"},
      {"userId":1,"message":"Bayside"},
      {"userId":2,"message":"Florence"},
      {"userId":1,"message":"Sutherland"},
      {"userId":2,"message":"Harper"},
      {"userId":1,"message":"Tomscot"},
      {"userId":2,"message":"Reinke"},
      {"userId":1,"message":"Lakewood"},
      {"userId":2,"message":"Kinsman"},
      {"userId":1,"message":"Cherokee"},
      {"userId":2,"message":"Declaration"},
      {"userId":1,"message":"Dennis"},
      {"userId":2,"message":"Chinook"},
      {"userId":1,"message":"Sachs"},
      {"userId":2,"message":"Continental"},
      {"userId":1,"message":"Barby"},
      {"userId":2,"message":"Darwin"},
      {"userId":1,"message":"American"},
      {"userId":2,"message":"Bonner"},
      {"userId":1,"message":"Springs"},
      {"userId":2,"message":"Hallows"},
      {"userId":1,"message":"Lyons"},
      {"userId":2,"message":"Coleman"},
      {"userId":1,"message":"Havey"},
      {"userId":2,"message":"Ramsey"},
      {"userId":1,"message":"Main"},
      {"userId":2,"message":"Logan"},
      {"userId":1,"message":"Badeau"},
      {"userId":2,"message":"Cascade"},
      {"userId":1,"message":"Dahle"},
      {"userId":2,"message":"Ridgeview"},
      {"userId":1,"message":"Weeping Birch"},
      {"userId":2,"message":"Ludington"},
      {"userId":1,"message":"Maryland"},
      {"userId":2,"message":"Larry"},
      {"userId":1,"message":"Forster"},
      {"userId":2,"message":"Drewry"},
      {"userId":1,"message":"Elgar"},
      {"userId":2,"message":"Little Fleur"},
      {"userId":1,"message":"Lillian"},
      {"userId":2,"message":"Meadow Valley"},
      {"userId":1,"message":"Shasta"},
      {"userId":2,"message":"Bay"},
      {"userId":1,"message":"Harbort"},
      {"userId":2,"message":"Granby"},
      {"userId":1,"message":"Oneill"},
      {"userId":2,"message":"Montana"},
      {"userId":1,"message":"Burrows"},
      {"userId":2,"message":"Park Meadow"},
      {"userId":1,"message":"Sachs"},
      {"userId":2,"message":"Grover"},
      {"userId":1,"message":"Maywood"},
      {"userId":2,"message":"Everett"},
      {"userId":1,"message":"Brentwood"},
      {"userId":2,"message":"Emmet"},
      {"userId":1,"message":"Steensland"},
      {"userId":2,"message":"Oak"},
      {"userId":1,"message":"Arrowood"},
      {"userId":2,"message":"Sheridan"},
      {"userId":1,"message":"Elmside"},
      {"userId":2,"message":"Fieldstone"},
      {"userId":1,"message":"Northfield"},
      {"userId":2,"message":"Mcbride"},
      {"userId":1,"message":"Shoshone"},
      {"userId":2,"message":"Truax"},
      {"userId":1,"message":"Bunker Hill"},
      {"userId":2,"message":"Briar Crest"},
      {"userId":1,"message":"Iowa"},
      {"userId":2,"message":"Armistice"},
      {"userId":1,"message":"Muir"},
      {"userId":2,"message":"Dakota"},
      {"userId":1,"message":"Thompson"},
      {"userId":2,"message":"Village"},
      {"userId":1,"message":"Glendale"},
      {"userId":2,"message":"Dapin"},
      {"userId":1,"message":"Golf Course"},
      {"userId":2,"message":"Tennessee"},
      {"userId":1,"message":"Jenna"},
      {"userId":2,"message":"Corry"},
      {"userId":1,"message":"Forest Dale"},
      {"userId":2,"message":"Monterey"},
      {"userId":1,"message":"Dorton"},
      {"userId":2,"message":"Swallow"},
      {"userId":1,"message":"Monument"},
      {"userId":2,"message":"Norway Maple"},
      {"userId":1,"message":"Stone Corner"},
      {"userId":2,"message":"New Castle"},
      {"userId":1,"message":"Mccormick"},
      {"userId":2,"message":"Fremont"},
      {"userId":1,"message":"Ilene"}
    ],
    last_message: '',
    imageUrl: 'https://i.insider.com/61d1c0e2aa741500193b2d18?width=1136&format=jpeg',
  }
]

const ROLES = [
  {
    userId: 1,
    chatId: 1,
    role: 'ADMIN'
  },
  {
    userId: 2,
    chatId: 1,
    role: 'USER'
  },
  {
    userId: 1,
    chatId: 2,
    role: 'USER'
  },
  {
    userId: 2,
    chatId: 2,
    role: 'ADMIN'
  }
]

module.exports = async () => {
  for (const seedChat of CHATS){
    await chat.upsert({
      where: {
        id: seedChat.id
      },
      create: {
        title: seedChat.title,
        imageUrl: seedChat.imageUrl,
        users: {
          connect: seedChat.userIds.map(el => ({
            id: el
          }))
        },
        messages: {
          create: seedChat.messages.map(el => ({
            userId: el.userId,
            message: el.message
          }))
        }
      },
      update: {}
    })
  }
}